### ISSUE TITLE
Unable to connect to Mastodon site raru.re

### ISSUE THREAD

**Issue by runrunrirun** [h3poteto/whalebird-desktop#2541]
After the latest update to Whalebird, I was unable to connect to raru.re which previously was working fine. 
I deleted the entry for raru.re from Whalebird and attempted to re-add it. 
Now Whalebird validates the site and displays this, but never shows the login dialog.

https://files.catbox.moe/ighfub.png

raru.re can be accessed fine from a browser.
I also have mstdn.io account in Whalebird and that works fine as well. raru.re was the second account.

macOS Catalina 10.15.7
Whalebird 4.4.1

**Comment by h3poteto** [comment]
OK, I will investigate.

**Comment by runrunrirun** [comment]
Retested with 4.4.2, still doesn't work.

The issue is that the button remains as 'Search' and doesn't change to 'Login' for this site.

I tried adding mastondon.social and that site works fine in Whalebird.

**Comment by h3poteto** [comment]
The reason is that `https://raru.re/api/v1/instance` returns 500 error.
There are two issue. First, the endpoint returns error. Second, Whalebird does not say any errors when the endpoint returns 500 error.

I will fix second issue.
@runrunrirun Could you please confirm your endpoint `https://raru.re/api/v1/instance` ?
