### ISSUE TITLE
Autostart possibilty with out active window 

### ISSUE THREAD

**Issue by ropfel** [h3poteto/whalebird-desktop#2660]
## Describe
A starting option i could launch out of the console without an active window. 
## Why

if I restart my system I want wattlebird staring without a window active on my screen to get notifications , for me my workflow is easier if i could abroad a active starting window like the element command 
_element-desktop --hidden_

**Comment by FibreFoX** [comment]
I do not see a good point behind `at the moment there is no advantage to do`.

Personally I would like to have Whalebird start "in the background" when I'm booting my system. I am one of those Windows users, that "shuts down" the computer. But when starting my system again, and other applications are showing their "slashscreens" in foreground, whalebird starts too, but due to "windows focus changes" it comes in foreground over the window I currently was working with.

So what is needed in order to have this feature "start minimized in system tray" (from a technical standpoint)?

**Comment by FibreFoX** [comment]
Oh and why is this tagged with "Linux"? Would be nice to have this especially on Windows too.
