### ISSUE TITLE
Can't reblog tweets, error "Failed to reblog"

### ISSUE THREAD

**Issue by foss-** [h3poteto/whalebird-desktop#3058]
## Description
Setup: Friendica connected with Twitter. Tweets are then showing up in friendica. Friendica account used in whalebird via mastodon API.

## How To Reproduce
1. press `Reblog` icon on any tweet showing up in timeline will result in error message `Failed to reblog`.
2. reproducible with squeet.me and pirati.ca account so not limited to specific friendica instance

Was going to setup test account to reproduce, but twitter won't let users do this without giving their phone number, but should be fairly easy to reproduce:

1. setup friendica squeet me account
2. connect friendica to a twitter account in friendica > settings > social networks > Twitter
3. setup friendica account in whalebird
4. follow a few twitter users by pasting their account URL in friendica > Contacts > Add Contact
5. wait for some tweets to show up in whalebird and press reblog icon

## Your Environment
 - macOS 11.6.2
 - Whalebird 4.5.0(final, which got pulled)
 - Instance: squeet.me and pirati.ca (both friendica)

Posts can be `Shared` (friendica terminology for reblog) when accessing account via web UI.

**Comment by foss-** [comment]
This sounds a lot like it might be related / the cause for this behavior: https://github.com/friendica/friendica/issues/11144

**Comment by nupplaphil** [comment]
Plz try again, the marked issue is fixed now

**Comment by foss-** [comment]
@nupplaphil - tried but the issue is persisting. Not sure how I can know when the fix has trickled down to pirati ca or squeet me.

**Comment by SpcCw** [comment]
At first I thought it was related to https://github.com/friendica/friendica/issues/11414 and tried Whalebird on my server but it turns out to be weird: I see in the webserver log that it tries to call `/api/v1/statuses/ID/reblog` and gets code 200 but Whalebird reports "Failed to reblog". For me it happens with any posts.

However if I try to call this manually, e.g. with `curl: curl -sS -u usr:pass --request POST --url "https://friends.deko.cloud/api/v1/statuses/10102824/reblog"` - it works so API seems to be working in principle, it is unclear why Whalebird request is different.

**Comment by foss-** [comment]
Another indicator this is a problem in Whalebird is, that reblogging or faving a post in Tusky works as expected with the same friendica accounts.

**Comment by h3poteto** [comment]
https://github.com/h3poteto/whalebird-desktop/issues/3327
