### ISSUE TITLE
Linux arm64 release?

### ISSUE THREAD

**Issue by Weathercold** [h3poteto/whalebird-desktop#4642]
Hello, I maintain the whalebird package in nixpkgs. When updating the package, I noticed that the latest release doesn't have a linux arm64 build (`Whalebird-5.1.0-linux-arm64.tar.bz2`). Can you add this asset to the release?

Edit: it seems that you removed it in https://github.com/h3poteto/whalebird-desktop/commit/b82590d22566d143284959417523a5881359e839. Is it not supported anymore?

**Comment by h3poteto** [comment]
https://github.com/h3poteto/whalebird-desktop/actions/runs/6379867682
Currently, since better-sqlite3 doesn't provide arm64 binary in their releases, we can't build arm64 binary.

However, I'm thinking of removing better-sqlite3 in the next major version (6.x.x ? maybe). So until then, arm64 binaries cannot be provided.

**Comment by Weathercold** [comment]
I see
